name = "Aegis"
author = "Aegis"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dd171fcbdb190474a95a7ace09556c7b71b826957c410a17fb4d938555a4ff5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
