name = "Aegis"
author = "Aegis"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed4871b0beffdf001ee022a82c06b2680dd895c311d2eaf10f5689a198eb7449"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
